// Pure markdown/text utilities shared by the editor, viewer and data layer.
// Keep this file dependency-free so it can run on server and client alike.

/** URL-safe slug from an arbitrary title ("Hello, World!" → "hello-world"). */
export function slugify(input: string): string {
  return input
    .normalize('NFKD')
    .replace(/[̀-ͯ]/g, '') // strip diacritics
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')
    .slice(0, 80) || 'article'
}

/**
 * Strips markdown syntax down to plain text. Good enough for excerpts and
 * word counting — not a full parser by design.
 */
export function stripMarkdown(markdown: string): string {
  return markdown
    .replace(/```[\s\S]*?```/g, ' ')        // fenced code blocks
    .replace(/`[^`]*`/g, ' ')               // inline code
    .replace(/!\[[^\]]*\]\([^)]*\)/g, ' ')  // images
    .replace(/\[([^\]]*)\]\([^)]*\)/g, '$1') // links → label
    .replace(/^#{1,6}\s+/gm, '')            // heading markers
    .replace(/^\s*(?:[-*+]|\d+\.)\s+(?:\[[ xX]\]\s+)?/gm, '') // list/task markers
    .replace(/^\s*>\s?/gm, '')              // blockquote markers
    .replace(/[*_~]{1,3}([^*_~]+)[*_~]{1,3}/g, '$1') // emphasis
    .replace(/\|/g, ' ')                    // table pipes
    .replace(/^[-=\s|:]+$/gm, '')           // hr / table separators
    .replace(/\s+/g, ' ')
    .trim()
}

export function countWords(markdown: string): number {
  const text = stripMarkdown(markdown)
  return text ? text.split(/\s+/).length : 0
}

const WORDS_PER_MINUTE = 225
const SECONDS_PER_IMAGE = 10

/** Hashnode-style reading time estimate, computed on the fly (never stored). */
export function estimateReadingTimeMinutes(markdown: string): number {
  const words = countWords(markdown)
  const images = (markdown.match(/!\[[^\]]*\]\([^)]*\)/g) ?? []).length
  const seconds = (words / WORDS_PER_MINUTE) * 60 + images * SECONDS_PER_IMAGE
  return Math.max(1, Math.round(seconds / 60))
}

/** First N characters of the article's plain text — used as a fallback description. */
export function excerptFromMarkdown(markdown: string, maxLength = 160): string {
  const text = stripMarkdown(markdown)
  if (text.length <= maxLength) return text
  return `${text.slice(0, maxLength).replace(/\s+\S*$/, '')}…`
}

export interface MarkdownHeading {
  depth: number // 1–6
  text: string
  id: string    // matches the ids generated by rehype-slug
}

/**
 * Extracts headings (outside code fences) for a future table of contents.
 * Ids follow the same github-slugger convention rehype-slug uses.
 */
export function extractHeadings(markdown: string): MarkdownHeading[] {
  const headings: MarkdownHeading[] = []
  const seen = new Map<string, number>()
  let inFence = false
  for (const line of markdown.split('\n')) {
    if (/^\s*(```|~~~)/.test(line)) { inFence = !inFence; continue }
    if (inFence) continue
    const match = /^(#{1,6})\s+(.+?)\s*#*\s*$/.exec(line)
    if (!match) continue
    const text = stripMarkdown(match[2])
    let id = slugify(text)
    const count = seen.get(id) ?? 0
    seen.set(id, count + 1)
    if (count > 0) id = `${id}-${count}`
    headings.push({ depth: match[1].length, text, id })
  }
  return headings
}
